# Generated by Django 4.1.5 on 2023-01-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_description_ticket_body'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollow',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userfollow',
            name='followed_user',
        ),
        migrations.RemoveField(
            model_name='userfollow',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='UserFollow',
        ),
    ]
