# Generated by Django 4.1.5 on 2023-01-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_ticket_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='review_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
