# Generated by Django 4.1.5 on 2023-01-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_ticket_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='review_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
