# Generated by Django 4.1.5 on 2023-01-16 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='description',
            new_name='body',
        ),
    ]
