# Generated by Django 4.1.5 on 2023-01-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_userfollow_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='review_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
