# Generated by Django 4.1.5 on 2023-01-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_ticket_review_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
