# Generated by Django 4.1.5 on 2023-01-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_ticket_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='review_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='has_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_pictures'),
        ),
    ]
